#!/bin/bash
# Backend

cd backend
composer install
php artisan key:generate
php artisan migrate
php artisan db:seed
chmod -R 777 storage
chmod -R 777 bootstrap

# Frontend
cd ..
cd frontend
bower install